# Generated by Django 4.1.13 on 2024-01-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_edited_alter_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
